"""empty message

Revision ID: 022659c893b2
Revises: a74a424a76d2
Create Date: 2024-09-13 15:59:07.331155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '022659c893b2'
down_revision = 'a74a424a76d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('additional_images', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('additional_images')

    # ### end Alembic commands ###
