"""empty message

Revision ID: 69965d1aa7e5
Revises: 680ab07749b5
Create Date: 2024-09-15 11:36:26.883164

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '69965d1aa7e5'
down_revision = '680ab07749b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email_verified')
        batch_op.drop_column('otp_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_code', mysql.VARCHAR(length=6), nullable=True))
        batch_op.add_column(sa.Column('email_verified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
