"""empty message

Revision ID: 707a8a8b9c5a
Revises: 69965d1aa7e5
Create Date: 2024-09-15 12:08:10.681367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '707a8a8b9c5a'
down_revision = '69965d1aa7e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('otp_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('otp_verified')
        batch_op.drop_column('otp')

    # ### end Alembic commands ###
