"""empty message

Revision ID: a74a424a76d2
Revises: 8a64762f1ee7
Create Date: 2024-09-12 17:16:47.389664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a74a424a76d2'
down_revision = '8a64762f1ee7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'category', ['parent_category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('parent_category_id')

    # ### end Alembic commands ###
