version: '3.8'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "4444"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql 
  adminer:
    image: adminer
    ports:
      - "8080:8080"

volumes:
  mysql_data:
    driver: local